//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int ID { get; set; }
        public int OrdersFK { get; set; }
        public int FoodFK { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
